### ISSUE TITLE
Add a configure or setuptools/setup.py script to check for bzr

### ISSUE THREAD

**Issue by krichter722** [felipec/git-remote-bzr#15]
It'd be more elegant to check whether `bzr` is installed in a build script. Due to the fact that the `Makefile` doesn't contain any too complicated commands and dependencies it could be replaced with a `setuptools`/`setup.py` script or a `configure` script could be introduced. It'd do that with `autoconf` even if might appear overkill for the size of the project.

I could provide the necessary changes as a pull request. Interested?

**Comment by felipec** [comment]
Yes. It might be good to add that check.

**Comment by felipec** [comment]
I'm not exactly sure what's the need being fulfilled here. Still interested?

**Comment by krichter722** [comment]
I'm no longer using the tool.

**Comment by felipec** [comment]
OK. For the record even if you are not using this tool the suggestion could benefit others, but I don't think there's many people using bzr these days anyway.
