### ISSUE TITLE
can't push to older bzr formats (pack-0.92)

### ISSUE THREAD

**Issue by vagrantc** [felipec/git-remote-bzr#16]
It was reported in https://bugs.debian.org/714038 that git-remote-bzr failed to push to a repository with an older bzr format (pack-0.92). Cloning the repository worked without issues.

I think the relevent error message is:

bzrlib.errors.IncompatibleRepositories: RemoteRepository(bzr+ssh://bazaar.launchpad.net/%2Bbranch/foxtrotgps/.bzr/)
is not compatible with
CHKInventoryRepository('file:///home/pabs/devel/misc/foxtrotgps/.git/bzr/.bzr/repository/')
different rich-root support

**Comment by felipec** [comment]
Is this still an issue?

**Comment by vagrantc** [comment]
I have not used git-remote-bzr in quite a while (most projects I work with switched to git), and it was eventually removed from Debian (over python 2 being deprecated).

**Comment by felipec** [comment]
All right. It served its purpose.
