### ISSUE TITLE
true roundtrip git -> bzr -> git (different repo) does not keep git hashes as stable as it could

### ISSUE THREAD

**Issue by zmanuel** [felipec/git-remote-bzr#24]
If you take a perfectly ordinary git branch with just regular commits and merges, well behaved authors and commit messages, push to a bzr branch, then import that bzr branch into a new git repository, you can end up with an exact replica of the first git branch.

However, several things can make the second git branch functionally equivalent to the first, but with different sha1 hashes. For example:
* rebases and cherry picks will have a different CommitDate and AuthorDate; bzr only has one native date field, so on reimport to git one will have been lost.
* an empty email in the source (`<>`) will be re-exported as `<Unknown>`, an empty name as `unknown`.
* commit messages can be weird. I don't know how it can be provoked with the regular UI, but at least with fast-import, you can have a git commit message that does not end in a newline; git-remote-bzr will then add one.

I have test cases in this branch: [https://github.com/zmanuel/git-remote-bzr/tree/recommit-roundtrip-test](url)

Now, I realize the following things:
* This is probably just a me problem. Usually, the marks cache should take care of keeping a bzr and git revision properly linked.
* Any workflow that relies on such roundtrip stability is foolish and certainly doomed; a single affected revision where it fails 'poisons' all its children.
* The stability of git-remote-bzr is bounded by the stability of git's fast-export/import, and guess what? That one already is unstable and an import of a fresh export can very well be different.

So I definitely won't complain if you close this as 'out of scope', or 'fundamentally impossible' or 'no, we don't want anyone to even entertain this idea'. I get that :)

But dammit, it's a matter of principle, export followed by import should be just the identity if the export format allows. So for me, on the git->bzr side, I made it so that the raw git properties of a commit that can't be reconstructed are saved to custom revision properties, and on the bzr->git process, they are restored. The branch is here: [https://github.com/zmanuel/git-remote-bzr/recommit-roundtrip](url)
So add another reason not to do this: 'we don't want the bzr properties to be polluted'. In the code's defence, it only does that when needed, so the perfectly regular branches mentioned in the introduction would be unaffected.

**Comment by felipec** [comment]
I completely agree that roundtrip support is very important. I just never got around to doing it.

I fetched your branched, cleaned up some stuff, and pushed the change. I cannot test it right now, but Travis-CI deson't complain.

Here's the final commit (476ba50c7d4446a37328544b29c2c569b0e77218). Thanks a lot!
