### ISSUE TITLE
switch to Python 3

### ISSUE THREAD

**Issue by pabs3** [felipec/git-remote-bzr#26]
git-remote-bzr was [removed from Debian](https://bugs.debian.org/936618) due to the transition away from Python 2 triggered by the impending [Python 2 EOL](https://pythonclock.org/). Please migrate the codebase to Python 3 so that git-remote-bzr can be used after 2020.

**Comment by felipec** [comment]
Bazaar is written in Python 2. If git-remote-bzr can't be in Debian, then neither can Bazaar.

**Comment by pabs3** [comment]
Bazaar has been removed from Debian and replaced by Breezy, which does support Python 3.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by felipec** [comment]
I would say this is completely dependent on issue #27.

**Comment by pabs3** [comment]
That is correct, since Bazaar is abandoned by Canonical it is very
unlikely to add Python 3 support, so using Breezy is required for
updating to Python 3.

I have an incomplete python3 branch in my fork of git-remote-bzr, it
depends on the changes in the breezy branch of my fork.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
