### ISSUE TITLE
How to get it work with a bzr repository that hasn't been pushed to launchpad and only resides on my computer 

### ISSUE THREAD

**Issue by PerfectCarl** [felipec/git-remote-bzr#9]
`git clone "bzr:file://~/Documents/Projects/myapp"` doesn't work.
It says : fatal: I don't handle protocol 'bzr:file'

**Comment by jdfrankland** [comment]
Hi
With a bzr repository repo.bzr in your working directory, just do
    git clone bzr::repo.bzr repo.git
and it will produce the new git repository repo.git
Hope this helps

**Comment by felipec** [comment]
First, it's `bzr::`, second, file urls are `file:///` (three slashes).
